### ISSUE TITLE
Is there is a way to add custom themes ??

### ISSUE THREAD

**Issue by d4g0** [mozilla/readability#604]
I have start to heavily use the reader view and i frequently have to set up my custom theme, im wandering if there is , or could be a way to include custom themes as options in the sidebar menu. Since the color changes are simple :
```css

body.custom-theme-name{
color:custom-color;
background-color: custom-background-color;
}
body.custom-theme-name a {
color:custom-anchor-color;
}

```
I think i will be simple add a “add theme” functionality with the above custom inputs.
So let me know if you think this will be usefull,
I will ad pull request.
