### ISSUE TITLE
code/pre blocks use sans-serif/serif instead of monospace

### ISSUE THREAD

**Issue by kbrosnan** [mozilla/readability#676]
## Steps to reproduce

- In Firefox Fenix, visit a page with code blocks (pre or code tags) ([example site](https://nyanpasu64.github.io/blog/an-unsafe-tour-of-rust-s-send-and-sync/)).
- Tap the Reader View button in the address bar.

### Expected behavior

Code blocks are rendered in a monospace font.

### Actual behavior

Code blocks are rendered in a sans-serif font.

This is due to https://github.com/mozilla-mobile/android-components/blob/584a6fc02a11a4c5928dcfd4089110871f242a75/components/feature/readerview/src/main/assets/extensions/readerview/readerview.css#L41-L47.

```css
.mozac-readerview-body.sans-serif * {
  font-family: sans-serif !important;
}

.mozac-readerview-body.serif * {
  font-family: serif !important;
}
```

These CSS rules override `pre` and `code` defaulting to a monospace font.

### Device information

* Device vendor / model and Android version: moto g power (2021), Android 10
* Firefox for Android version: Nightly 210227 17:01 (Build #2015795787); AC: 74.0.20210227143138, 5437eb229; GV: 88.0a1-20210227094458; AS: 72.1.0
